Feature/16 create repository using GitHub api
projectopia/generator pull request #24
Opened 2024-01-08 13:38 UTC by TuanTran0910

2024-01-08 14:43 UTC, lelouvincx reviewed
What formatter are you using? Doesn't look like `black`.

2024-01-08 14:48 UTC, lelouvincx commented
What formatter are you using? Doesn't look like `black`.

2024-01-08 14:49 UTC, TuanTran0910 commented on backend/repository/__init__.py
Oh, It was my fault. I will change it

2024-01-08 14:50 UTC, TuanTran0910 commented on backend/repository/repository.py
> +from typing import List, Dict
Yes, will use it.

2024-01-08 14:51 UTC, TuanTran0910 commented
I use ```Prettier formatter```.

2024-01-08 14:52 UTC, lelouvincx commented
> I use `Prettier formatter`.

I think we should use `black`. Let's discuss later.

2024-01-09 14:43 UTC, TuanTran0910 commented on backend/repository/repository.py
> +    def _get_username(self):
Added !

2024-01-09 14:44 UTC, TuanTran0910 commented on backend/repository/__init__.py
I have changed to the correct path.

2024-01-09 14:44 UTC, TuanTran0910 commented on backend/repository/repository.py
> +from typing import List, Dict
I have added Pydantic in the source code.

2024-01-09 16:02 UTC, TuanTran0910 commented on backend/repository/repository.py
> +            self.add_collaborator(username)
I think it's not a big deal problem. Just keep those 2 functions .

2024-01-13 12:47 UTC, TuanTran0910 commented on backend/utils/github/repository.py
> +        self._logger = logging.getLogger("Projectopia Repository")
Changed to ```__name__```!

2024-01-13 12:49 UTC, TuanTran0910 commented on backend/utils/github/repository.py
> +            self._logger.error(f"Failed to create repository. Error: {response.text}")
Changed to use ```self._logger.exception``` instead ```self._logger.error```

2024-01-13 13:07 UTC, TuanTran0910 commented on backend/utils/github/config.py
> +    version: str = Field(pattern=r"\d{4}-\d{2}-\d{2}", default="2022-11-28")
Added ```constant.py```.

2024-01-13 13:12 UTC, lelouvincx approved these changes
LGTM!

2024-01-13 13:27 UTC, greyyT requested changes

2024-01-13 13:27 UTC, greyyT commented on backend/utils/github/repository.py
> +class PersonalRepository(BaseRepository):
Changing the response from methods in this class (PersonalRepository) to either True or False might be a better approach (ie: if the result of the create method is success, it should return True).

Here's an example of how the modified create method might look:

```python
class PersonalRepository:
    def create(self, data):
        try:
            # Code logic for creating the record
            # ...
            # If the create operation is successful
            return True
        except Exception as e:
            # If there is an error or issue during the create operation
            # Log the error or handle it as needed
            # ...
            return False
```

By returning True or False from the methods in the PersonalRepository class, you can easily determine whether the user's action was successful or not in the Flask backend. This allows you to handle any future actions or address any issues accordingly.

2024-01-14 09:37 UTC, TuanTran0910 commented on backend/utils/github/repository.py
> +class PersonalRepository(BaseRepository):
> It would be better to change the response of methods in the `PersonalRepository` class to either `True` or `False`. For example, if the `create` method is successful, it should return `True`.
> 
> Here's an example of how the modified `create` method might look:
> 
> ```python
> class PersonalRepository(BaseRepository):
>     def create(self, data):
>         try:
>             # Code logic for creating the record
>             # ...
>             # If the create operation is successful
>             return True
>         except Exception as e:
>             # If there is an error or issue during the create operation
>             # Log the error or handle it as needed
>             # ...
>             return False
> ```
> 
> By returning `True` or `False` from the methods in the `PersonalRepository` class, you can easily determine whether the user's action was successful or not in the Flask backend. This allows you to handle any future actions or address any issues accordingly.

I have modify the return statement to True/False return. The code will be changed like this:
```python
# In backend/utils/github/repository.py
# ...
if response.status_code == 201:
            self._logger.info("Repository created successfully!")
        else:
            self._logger.exception(
                f"Failed to create repository. Error: {response.text}"
            )
            return False
        return True
```

2024-01-14 09:52 UTC, greyyT commented on backend/utils/github/repository.py
> +class PersonalRepository(BaseRepository):
Not only the `create` method but also almost all of your methods in `PersonalRepository` should return a boolean value. This is important for future scenarios, such as implementing an api endpoint for adding collaborators.

For instance, when using the `add_collaborator` method of the `PersonalRepository` class in your API endpoint, the method currently only logs the status without returning any information. This lack of return value makes it impossible for your code to determine whether the user's action was successful or not, preventing you from notifying the user by returning an appropriate error status.

2024-01-14 10:06 UTC, TuanTran0910 commented on backend/utils/github/repository.py
> +class PersonalRepository(BaseRepository):
Yes, I agree that this is a needed change. I have modified in the code and made a push on branch ```feature/16-create-repository-using-github-api```.

2024-01-14 10:12 UTC, greyyT approved these changes
LGTM!

2024-01-15 02:59 UTC, merged